export type SpriteData = {
  palette: Readonly<Record<string, string>>;
  map: readonly string[];
};

// 16x16 EGA pixel art. Keys are the contract with consumers (Sprite name,
// FileTable icons): keep them stable.
export const sprites = {
  jar: {
    palette: {
      K: "#000000",
      y: "#FFFF55",
      W: "#55FFFF",
      g: "#555555",
      b: "#AA5500",
    },
    map: [
      "................",
      ".....KKKKKK.....",
      "....KyyyyyyK....",
      "....KKKKKKKK....",
      "...KgWggggggK...",
      "...KgWggggggK...",
      "...KggggggggK...",
      "...Kg.bb.gggK...",
      "...Kg.bb.gggK...",
      "...Kg.bb.bbgK...",
      "...Kg.bb.bbgK...",
      "...KggggggggK...",
      "...KggggggggK...",
      "...KKKKKKKKK....",
      "................",
      "................",
    ],
  },
  folder: {
    palette: {
      K: "#000000",
      y: "#FFFF55",
    },
    map: [
      "................",
      "................",
      "................",
      ".KKKKK..........",
      ".KyyyyKKKKKKKKK.",
      ".KyyyyyyyyyyyyK.",
      ".KyyyyyyyyyyyyK.",
      ".KyyyyyyyyyyyyK.",
      ".KyyyyyyyyyyyyK.",
      ".KyyyyyyyyyyyyK.",
      ".KyyyyyyyyyyyyK.",
      ".KyyyyyyyyyyyyK.",
      ".KKKKKKKKKKKKKK.",
      "................",
      "................",
      "................",
    ],
  },
  folderOpen: {
    palette: {
      K: "#000000",
      y: "#FFFF55",
    },
    map: [
      "................",
      "................",
      "................",
      ".KKKKK..........",
      ".KyyyyKKKKKKKKK.",
      ".KyyyyyyyyyyyyK.",
      ".KyyyyyyyyyyyyK.",
      ".KyyKKKKKKKKKKKK",
      ".KyKyyyyyyyyyyyK",
      ".KKKyyyyyyyyyyyK",
      ".KyyyyyyyyyyyyyK",
      ".KyyyyyyyyyyyyK.",
      ".KKKKKKKKKKKKK..",
      "................",
      "................",
      "................",
    ],
  },
  file: {
    palette: {
      K: "#000000",
      W: "#FFFFFF",
      g: "#555555",
    },
    map: [
      "................",
      "...KKKKKKK......",
      "...KWWWWWK......",
      "...KWWWWWWK.....",
      "...KWWWWWWWK....",
      "...KWWWWWWWWK...",
      "...KWWWWWWWWK...",
      "...KWggggggWK...",
      "...KWWWWWWWWK...",
      "...KWggggggWK...",
      "...KWWWWWWWWK...",
      "...KWgggggggK...",
      "...KWWWWWWWWK...",
      "...KKKKKKKKKK...",
      "................",
      "................",
    ],
  },
  // The errata file: the same sheet as a document, marked in red.
  errata: {
    palette: {
      K: "#000000",
      W: "#FFFFFF",
      r: "#FF5555",
    },
    map: [
      "................",
      "...KKKKKKK......",
      "...KWWWWWK......",
      "...KWWWWWWK.....",
      "...KWWWWWWWK....",
      "...KWWWrrWWWK...",
      "...KWWWrrWWWK...",
      "...KWWWrrWWWK...",
      "...KWWWrrWWWK...",
      "...KWWWrrWWWK...",
      "...KWWWWWWWWK...",
      "...KWWWrrWWWK...",
      "...KWWWWWWWWK...",
      "...KKKKKKKKKK...",
      "................",
      "................",
    ],
  },
  speech: {
    palette: {
      K: "#000000",
      W: "#FFFFFF",
    },
    map: [
      "................",
      "................",
      "................",
      "..KKKKKKKKKKK...",
      ".KWWWWWWWWWWWK..",
      ".KWWWWWWWWWWWK..",
      ".KWWWWWWWWWWWK..",
      ".KWWKWWKWWKWWK..",
      ".KWWWWWWWWWWWK..",
      ".KWWWWWWWWWWWK..",
      ".KWWWWWWWWWWWK..",
      ".KWWWWKKKKKKKK..",
      "..KWWK..........",
      "..KKK...........",
      "................",
      "................",
    ],
  },
  book: {
    palette: {
      K: "#000000",
      W: "#FFFFFF",
      g: "#555555",
    },
    map: [
      "................",
      "................",
      "................",
      "....KKK..KKK....",
      "..KKWWWKKWWWKK..",
      ".KWWWWWKKWWWWWK.",
      ".KWgggWKKWgggWK.",
      ".KWWWWWKKWWWWWK.",
      ".KWgggWKKWgggWK.",
      ".KWWWWWKKWWWWWK.",
      ".KWWWWWKKWWWWWK.",
      ".KKKKKKKKKKKKKK.",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  box: {
    palette: {
      K: "#000000",
      b: "#AA5500",
      c: "#FFFF55",
    },
    map: [
      "................",
      "................",
      "..KKKKKKKKKKKK..",
      "..KbbbbccbbbbK..",
      "..KKKKKccKKKKK..",
      "..KbbbbccbbbbK..",
      "..KbbbbccbbbbK..",
      "..KbbbbccbbbbK..",
      "..KbbbbccbbbbK..",
      "..KbbbbccbbbbK..",
      "..KbbbbccbbbbK..",
      "..KbbbbccbbbbK..",
      "..KKKKKKKKKKKK..",
      "................",
      "................",
      "................",
    ],
  },
  ticket: {
    palette: {
      K: "#000000",
      y: "#FFFF55",
    },
    map: [
      "................",
      "................",
      "................",
      ".KKKKKKKKKKKKKK.",
      ".KyyyyyyyyyyyyK.",
      ".KyyyyyyyyKyyyK.",
      "..KyyyyyyyyyyK..",
      "..KyyyyyyyKyyK..",
      "..KyyyyyyyyyyK..",
      ".KyyyyyyyyKyyyK.",
      ".KyyyyyyyyyyyyK.",
      ".KyyyyyyyyyyyyK.",
      ".KKKKKKKKKKKKKK.",
      "................",
      "................",
      "................",
    ],
  },
  check: {
    palette: {
      K: "#000000",
      W: "#FFFFFF",
      n: "#009900",
    },
    map: [
      "................",
      "...KKKKKKK......",
      "...KWWWWWK......",
      "...KWWWWWWK.....",
      "...KWWWWWWWK....",
      "...KWWWWWWWWK...",
      "...KWWWWWWnWK...",
      "...KWnWWWnWWK...",
      "...KWWnWnWWWK...",
      "...KWWWnWWWWK...",
      "...KWWWWWWWWK...",
      "...KWWWWWWWWK...",
      "...KWWWWWWWWK...",
      "...KKKKKKKKKK...",
      "................",
      "................",
    ],
  },
  key: {
    palette: {
      K: "#000000",
      y: "#FFFF55",
    },
    map: [
      "................",
      "................",
      "......KKKK......",
      ".....KyyyyK.....",
      "....KyyKKyyK....",
      "....KyK..KyK....",
      "...KyK....KyK...",
      "....KyK..KyK....",
      "....KyyKKyyK....",
      ".....KyyyyK.....",
      "......KyyK......",
      "......KyyyKKK...",
      "......KyyyyyK...",
      "......KKKKKKK...",
      "................",
      "................",
    ],
  },
  mail: {
    palette: {
      K: "#000000",
      W: "#FFFFFF",
    },
    map: [
      "................",
      "................",
      "................",
      "................",
      "..KKKKKKKKKKKK..",
      "..KWWWWWWWWWWK..",
      "..KWKWWWWWWKWK..",
      "..KWWKWWWWKWWK..",
      "..KWWWKWWKWWWK..",
      "..KWWWWKKWWWWK..",
      "..KWWWWWWWWWWK..",
      "..KKKKKKKKKKKK..",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  person: {
    palette: {
      K: "#000000",
      l: "#AAAAAA",
    },
    map: [
      "................",
      "................",
      "......KKKK......",
      ".....KllllK.....",
      ".....KllllK.....",
      ".....KllllK.....",
      ".....KllllK.....",
      "......KllK......",
      ".....KllllK.....",
      "....KllllllK....",
      "....KllllllK....",
      "...KllllllllK...",
      "...KllllllllK...",
      "...KllllllllK...",
      "...KKKKKKKKKK...",
      "................",
    ],
  },
  gear: {
    palette: {
      K: "#000000",
      l: "#AAAAAA",
      g: "#555555",
    },
    map: [
      "................",
      "......KKKK......",
      "......KllK......",
      "...KKKllllKKK...",
      "...KlllKKlllK...",
      "...KllKggKllK...",
      ".KKllKggggKllKK.",
      ".KlllKggggKlllK.",
      ".KlllKggggKlllK.",
      ".KKllKggggKllKK.",
      "...KllKggKllK...",
      "...KlllKKlllK...",
      "...KKKllllKKK...",
      "......KllK......",
      "......KKKK......",
      "................",
    ],
  },
  door: {
    palette: {
      K: "#000000",
      g: "#555555",
      b: "#AA5500",
      y: "#FFFF55",
    },
    map: [
      "................",
      "................",
      "..KKKKKKKKKKKK..",
      "..KgggKbbbbbKK..",
      "..KgggKbbbbbKK..",
      "..KgggKbbbbbKK..",
      "..KgggKbbbbbKK..",
      "..KgggKbybbbKK..",
      "..KgggKbybbbKK..",
      "..KgggKbbbbbKK..",
      "..KgggKbbbbbKK..",
      "..KgggKbbbbbKK..",
      "..KgggKbbbbbKK..",
      "..KKKKKKKKKKKK..",
      "................",
      "................",
    ],
  },
  // Editor toolbar icons (20x20): the same EGA hand, more room for the glyph.
  code: {
    palette: {
      K: "#000000",
    },
    map: [
      "....................",
      "....................",
      "....................",
      "....................",
      ".....KK......KK.....",
      "....KK........KK....",
      "...KK......KK..KK...",
      "..KK.......KK...KK..",
      ".KK.......KK.....KK.",
      ".KK.......KK.....KK.",
      ".KK.....KK.......KK.",
      "..KK....KK......KK..",
      "...KK..KK......KK...",
      "....KK.KK.....KK....",
      ".....KK......KK.....",
      "......KK....KK......",
      "....................",
      "....................",
      "....................",
      "....................",
    ],
  },
  block: {
    palette: {
      K: "#000000",
      W: "#FFFFFF",
      g: "#555555",
    },
    map: [
      "....................",
      "....................",
      "....KKKKKKKKKKKK....",
      "....KWWWWWWWWWWK....",
      "....KWWWWWWWWWWK....",
      "....KWggggggggWK....",
      "....KWWWWWWWWWWK....",
      "....KWggggggWWWK....",
      "....KWWWWWWWWWWK....",
      "....KWggggggggWK....",
      "....KWWWWWWWWWWK....",
      "....KWggggggWWWK....",
      "....KWWWWWWWWWWK....",
      "....KWggggggggWK....",
      "....KWWWWWWWWWWK....",
      "....KWWWWWWWWWWK....",
      "....KWWWWWWWWWWK....",
      "....KKKKKKKKKKKK....",
      "....................",
      "....................",
    ],
  },
  link: {
    palette: {
      K: "#000000",
      W: "#FFFFFF",
    },
    map: [
      "....................",
      "....................",
      "....................",
      "....................",
      ".........KKKKKKKKK..",
      ".........KWWWWWWWK..",
      "..KKKKKKKKK.....WK..",
      "..KWWWWWWKK.....WK..",
      "..KW.....KK.....WK..",
      "..KW.....KK.....WK..",
      "..KW.....KK.....WK..",
      "..KW.....KK.....WK..",
      "..KW.....KKWWWWWWK..",
      "..KW.....KKKKKKKKK..",
      "..KWWWWWWWK.........",
      "..KKKKKKKKK.........",
      "....................",
      "....................",
      "....................",
      "....................",
    ],
  },
  image: {
    palette: {
      K: "#000000",
      W: "#FFFFFF",
      y: "#FFFF55",
      g: "#555555",
    },
    map: [
      "....................",
      "....................",
      "....................",
      "..KKKKKKKKKKKKKKKK..",
      "..KWWWWWWWWWWWWWWK..",
      "..KWWWWWWWWWKKKKWK..",
      "..KWWWWWWWWWKyyKWK..",
      "..KWWWWWWWWWKyyKWK..",
      "..KWWWWWWWWWKKKKWK..",
      "..KWWWWWWWWWWWWWWK..",
      "..KWWWWWWWWWWWWWWK..",
      "..KWWWgWWWWWWWWWWK..",
      "..KWWgggWWWWWgWWWK..",
      "..KWgggggWWWgggWWK..",
      "..KggggggggggggWWK..",
      "..KggggggggggggggK..",
      "..KKKKKKKKKKKKKKKK..",
      "....................",
      "....................",
      "....................",
    ],
  },
} as const satisfies Record<string, SpriteData>;

export type SpriteName = keyof typeof sprites;
